############################
## Comments
############################
[comments]
  # Comment provider:
  provider = "giscus"

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = false, project = false, publication = true, talk = false}

  # Configuration of giscus
  [comments.giscus]
    repo = "<data-repo>" # Repo where the comments will live
    repo_id = "<data-repo-id>" # Repo where the comments will live
    category = "Announcements" # Repo where the comments will live
    category_id = "<data-category-id>" # Repo where the comments will live
    mapping = "pathname" # How Utterances will match comment to page
    label = "comment" # Label applied to issue by utteranc.es bot
    theme = "light" # What theme to use
    reactions_enabled = 0