############################
## Comments
############################
[comments]
  # Comment provider:
  provider = "giscus"

  # Which page types are commentable?
  commentable = {page = true, post = true, docs = false, project = false, publication = true, talk = false}

  # Configuration of giscus
  [comments.giscus]
 repo = "wiredhikari/pkgcraft.gihub.io" # Entering repo will enable giscus
  repo_id = "453687247"
  category = "Comments"
  category_id = "enter-category-id"
  mapping = "pathname"
  reactions-enabled = "1"
  emit-metadata = "0"
  theme = "light"
  lang = "en"
